[build]
command = "pnpm run build"
publish = "dist"

[dev]
command = "pnpm run dev"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = 'max-age=63072000; includeSubDomains; preload'