[build]
command = "pnpm run build && cp ./_headers ./dist/_headers"
publish = "dist"

[dev]
command = "pnpm run dev"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self';"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self 'https://www.webstarsltd.com'), microphone=()"
    Strict-Transport-Security = 'max-age=63072000; includeSubDomains; preload'
    