[build]
command = "pnpm run build"
publish = "dist"

[dev]
command = "pnpm run dev"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self 'https://www.webstarsltd.com'), microphone=()"